// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UploadAcceptedStatus.
const (
	QUEUED UploadAcceptedStatus = "QUEUED"
)

// Valid indicates whether the value is a known member of the UploadAcceptedStatus enum.
func (e UploadAcceptedStatus) Valid() bool {
	switch e {
	case QUEUED:
		return true
	default:
		return false
	}
}

// ErrorResponse Standardized error shape, identical across all Sublio services.
type ErrorResponse struct {
	// Code Machine-readable error code, e.g. MISSING_JOB_ID, MISSING_IDEMPOTENCY_KEY, MISSING_VIDEO_FIELD, UNSUPPORTED_MEDIA_TYPE, EXECUTABLE_FORBIDDEN, FILE_TOO_LARGE, NOT_FOUND, RANGE_NOT_SATISFIABLE, INTERNAL_SERVER_ERROR.
	Code string `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`

	// TraceId Ties this error to a Tempo trace.
	TraceId *string `json:"traceId,omitempty"`
}

// UploadAccepted defines model for UploadAccepted.
type UploadAccepted struct {
	FileName *string `json:"fileName,omitempty"`

	// FolderId UUID folder the video was stored under; used to build the playback URL.
	FolderId *openapi_types.UUID   `json:"folderId,omitempty"`
	JobId    *string               `json:"jobId,omitempty"`
	Status   *UploadAcceptedStatus `json:"status,omitempty"`
}

// UploadAcceptedStatus defines model for UploadAccepted.Status.
type UploadAcceptedStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// UploadVideoMultipartBody defines parameters for UploadVideo.
type UploadVideoMultipartBody struct {
	// Video The video file to upload. Validated server-side by magic bytes (MP4/MKV/AVI only); the original filename is discarded and is not used for storage. Maximum size 2GB.
	Video openapi_types.File `json:"video"`
}

// UploadVideoParams defines parameters for UploadVideo.
type UploadVideoParams struct {
	// JobId Client-supplied job identifier, correlated with the queued task.
	JobId string `form:"jobId" json:"jobId"`

	// IdempotencyKey Client-generated UUID identifying this upload request, stored with a unique constraint. If a request arrives with an Idempotency-Key that was already used, the original upload result is returned unchanged (same 202, same jobId/folderId/fileName) instead of saving the file a second time — this is what makes a client retry after a network timeout safe. See backend/08-scalability.md.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetVideoParams defines parameters for GetVideo.
type GetVideoParams struct {
	// Range Standard HTTP Range header, e.g. `bytes=0-1023`.
	Range *string `json:"Range,omitempty"`
}

// UploadVideoMultipartRequestBody defines body for UploadVideo for multipart/form-data ContentType.
type UploadVideoMultipartRequestBody UploadVideoMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// UploadVideo Upload a video for processing
	// (POST /upload)
	UploadVideo(w http.ResponseWriter, r *http.Request, params UploadVideoParams)
	// GetVideo Stream a stored video
	// (GET /video/{folderId}/{fileName})
	GetVideo(w http.ResponseWriter, r *http.Request, folderId openapi_types.UUID, fileName string, params GetVideoParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// UploadVideo Upload a video for processing
// (POST /upload)
func (_ Unimplemented) UploadVideo(w http.ResponseWriter, r *http.Request, params UploadVideoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVideo Stream a stored video
// (GET /video/{folderId}/{fileName})
func (_ Unimplemented) GetVideo(w http.ResponseWriter, r *http.Request, folderId openapi_types.UUID, fileName string, params GetVideoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadVideo operation middleware
func (siw *ServerInterfaceWrapper) UploadVideo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadVideoParams

	// ------------- Required query parameter "jobId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "jobId", r.URL.Query(), &params.JobId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "jobId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobId", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadVideo(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVideo operation middleware
func (siw *ServerInterfaceWrapper) GetVideo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "folderId" -------------
	var folderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "folderId", chi.URLParam(r, "folderId"), &folderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "folderId", Err: err})
		return
	}

	// ------------- Path parameter "fileName" -------------
	var fileName string

	err = runtime.BindStyledParameterWithOptions("simple", "fileName", chi.URLParam(r, "fileName"), &fileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileName", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVideoParams

	headers := r.Header

	// ------------- Optional header parameter "Range" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Range")]; found {
		var Range string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Range", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Range", valueList[0], &Range, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Range", Err: err})
			return
		}

		params.Range = &Range

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVideo(w, r, folderId, fileName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/upload", wrapper.UploadVideo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/video/{folderId}/{fileName}", wrapper.GetVideo)
	})

	return r
}
