// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for JobStatus.
const (
	CREATED             JobStatus = "CREATED"
	DONE                JobStatus = "DONE"
	ERROR               JobStatus = "ERROR"
	PROCESSINGSUBTITLES JobStatus = "PROCESSING_SUBTITLES"
	QUEUED              JobStatus = "QUEUED"
	TRANSCRIBING        JobStatus = "TRANSCRIBING"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case CREATED:
		return true
	case DONE:
		return true
	case ERROR:
		return true
	case PROCESSINGSUBTITLES:
		return true
	case QUEUED:
		return true
	case TRANSCRIBING:
		return true
	default:
		return false
	}
}

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// FilePath Path to the uploaded video on the shared volume, as returned by media-service (e.g. processed/{uuid}/video.mp4).
	FilePath string `json:"filePath"`
}

// CreateJobResponse defines model for CreateJobResponse.
type CreateJobResponse struct {
	JobId *openapi_types.UUID `json:"jobId,omitempty"`
}

// ErrorResponse Standardized error shape, identical across all Sublio services.
type ErrorResponse struct {
	// Code Machine-readable error code, e.g. MISSING_FILE_PATH, MISSING_IDEMPOTENCY_KEY, QUEUE_DEPTH_EXCEEDED, NOT_FOUND, FORBIDDEN, JOB_ALREADY_TERMINAL.
	Code string `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`

	// TraceId Ties this error to a Tempo trace.
	TraceId *string `json:"traceId,omitempty"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Message Human-readable status detail (e.g. current pipeline step, or error detail).
	Message *string `json:"message,omitempty"`

	// Result Present only once status is DONE.
	Result *struct {
		SubtitleId *openapi_types.UUID `json:"subtitleId,omitempty"`
		VideoUrl   *string             `json:"videoUrl,omitempty"`
	} `json:"result,omitempty"`

	// Status Linear pipeline progression, with ERROR reachable from any in-progress state: CREATED → QUEUED → TRANSCRIBING → PROCESSING_SUBTITLES → DONE, or → ERROR at any point.
	Status    *JobStatus `json:"status,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// JobStatus Linear pipeline progression, with ERROR reachable from any in-progress state: CREATED → QUEUED → TRANSCRIBING → PROCESSING_SUBTITLES → DONE, or → ERROR at any point.
type JobStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// JobId defines model for JobId.
type JobId = openapi_types.UUID

// CreateJobParams defines parameters for CreateJob.
type CreateJobParams struct {
	// IdempotencyKey Client-generated UUID identifying this logical create request, stored with a unique constraint on the jobs table. If a request arrives with an Idempotency-Key that already exists, the existing job is returned unchanged (same 201, same jobId) instead of creating a duplicate — this is what makes a client retry after a network timeout safe. See backend/08-scalability.md.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateJob Create a processing job
	// (POST /jobs)
	CreateJob(w http.ResponseWriter, r *http.Request, params CreateJobParams)
	// CancelJob Cancel a job
	// (DELETE /jobs/{id})
	CancelJob(w http.ResponseWriter, r *http.Request, id JobId)
	// GetJob Get current job status
	// (GET /jobs/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id JobId)
	// StreamJobProgress Stream live job progress (SSE)
	// (GET /jobs/{id}/progress)
	StreamJobProgress(w http.ResponseWriter, r *http.Request, id JobId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// CreateJob Create a processing job
// (POST /jobs)
func (_ Unimplemented) CreateJob(w http.ResponseWriter, r *http.Request, params CreateJobParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CancelJob Cancel a job
// (DELETE /jobs/{id})
func (_ Unimplemented) CancelJob(w http.ResponseWriter, r *http.Request, id JobId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetJob Get current job status
// (GET /jobs/{id})
func (_ Unimplemented) GetJob(w http.ResponseWriter, r *http.Request, id JobId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StreamJobProgress Stream live job progress (SSE)
// (GET /jobs/{id}/progress)
func (_ Unimplemented) StreamJobProgress(w http.ResponseWriter, r *http.Request, id JobId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateJobParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelJob operation middleware
func (siw *ServerInterfaceWrapper) CancelJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamJobProgress operation middleware
func (siw *ServerInterfaceWrapper) StreamJobProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamJobProgress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/jobs", wrapper.CreateJob)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/jobs/{id}", wrapper.CancelJob)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/jobs/{id}", wrapper.GetJob)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/jobs/{id}/progress", wrapper.StreamJobProgress)
	})

	return r
}
