#!/usr/bin/env bash
# infra/vault/scripts/apply-vault-config.sh
#
# Idempotently applies all policies and AppRole roles described in roles.yaml.
# Run MANUALLY, FROM THE HOST, once during initial setup and again whenever
# a new role is added to roles.yaml. NOT part of docker-compose up.
#
# Requires: vault CLI, yq (mikefarah/yq, NOT the python version)
# Requires: VAULT_ADDR and VAULT_TOKEN (root token or admin) in the environment
#
# Compatible with bash 3.2 (macOS system bash) - no associative arrays
# (declare -A), those only appeared in bash 4.0.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="${SCRIPT_DIR}/../roles.yaml"
POLICIES_DIR="${SCRIPT_DIR}/../policies"

if ! command -v yq &> /dev/null; then
  echo "Error: yq is required (https://github.com/mikefarah/yq)" >&2
  exit 1
fi

if [[ -z "${VAULT_ADDR:-}" || -z "${VAULT_TOKEN:-}" ]]; then
  echo "Error: VAULT_ADDR and VAULT_TOKEN must be set in the environment" >&2
  exit 1
fi

vault auth enable approle 2>/dev/null || true

count=$(yq '.roles | length' "${MANIFEST}")
echo "Found roles in manifest: ${count}"
echo "---"

# Instead of an associative array (declare -A, requires bash 4+) -
# accumulate the result line by line in a plain list variable.
ROLE_IDS_SUMMARY=""

for i in $(seq 0 $((count - 1))); do
  name=$(yq -r ".roles[$i].name" "${MANIFEST}")
  policy_file=$(yq -r ".roles[$i].policy_file" "${MANIFEST}")
  token_ttl=$(yq -r ".roles[$i].token_ttl" "${MANIFEST}")
  token_max_ttl=$(yq -r ".roles[$i].token_max_ttl" "${MANIFEST}")
  secret_id_ttl=$(yq -r ".roles[$i].secret_id_ttl" "${MANIFEST}")
  secret_id_num_uses=$(yq -r ".roles[$i].secret_id_num_uses" "${MANIFEST}")

  policy_name="${policy_file%.hcl}"
  policy_path="${POLICIES_DIR}/${policy_file}"

  if [[ ! -f "${policy_path}" ]]; then
    echo "Error: policy file not found: ${policy_path}" >&2
    exit 1
  fi

  echo "==> [${name}] policy: ${policy_name}"
  vault policy write "${policy_name}" "${policy_path}" > /dev/null

  echo "==> [${name}] approle role"
  vault write "auth/approle/role/${name}" \
      token_policies="${policy_name}" \
      token_ttl="${token_ttl}" \
      token_max_ttl="${token_max_ttl}" \
      secret_id_ttl="${secret_id_ttl}" \
      secret_id_num_uses="${secret_id_num_uses}" \
      > /dev/null

  role_id=$(vault read -field=role_id "auth/approle/role/${name}/role-id")
  env_var=$(echo "${name}" | tr '[:lower:]-' '[:upper:]_')
  ROLE_IDS_SUMMARY="${ROLE_IDS_SUMMARY}${env_var}_ID=${role_id}
"
  echo "    role_id: ${role_id}"
  echo "---"
done

echo ""
echo "Done. Roles applied: ${count}"
echo ""
echo "Copy the role_id into .env (it's not a secret, safe to store in the open):"
echo ""
printf '%s' "${ROLE_IDS_SUMMARY}"
echo ""
echo "secret_id is NOT generated by this script - bootstrap-approle.sh issues it"
echo "fresh on every docker-compose startup (see README)."