#!/usr/bin/env bash
# infra/vault/scripts/apply-vault-config.sh
#
# Idempotently applies all policies and AppRole roles described in roles.yaml.
# Run MANUALLY, FROM THE HOST, once during initial setup and again whenever
# a new role is added to roles.yaml. NOT part of docker-compose up.
#
# Requires: vault CLI, yq (mikefarah/yq, NOT the python version)
# Requires: VAULT_ADDR and VAULT_TOKEN (root token or admin) in the environment
#
# Compatible with bash 3.2 (macOS system bash) - no associative arrays
# (declare -A), those only appeared in bash 4.0.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="${SCRIPT_DIR}/../roles.yaml"
POLICIES_DIR="${SCRIPT_DIR}/../policies"

if ! command -v yq &> /dev/null; then
  echo "Error: yq is required (https://github.com/mikefarah/yq)" >&2
  exit 1
fi

if [[ -z "${VAULT_ADDR:-}" || -z "${VAULT_TOKEN:-}" ]]; then
  echo "Error: VAULT_ADDR and VAULT_TOKEN must be set in the environment" >&2
  exit 1
fi

vault auth enable approle 2>/dev/null || true

count=$(yq '.roles | length' "${MANIFEST}")
echo "Found roles in manifest: ${count}"
echo "---"

# Instead of an associative array (declare -A, requires bash 4+) -
# accumulate the result line by line in a plain list variable.
ROLE_IDS_SUMMARY=""

for i in $(seq 0 $((count - 1))); do
  name=$(yq -r ".roles[$i].name" "${MANIFEST}")
  policy_file=$(yq -r ".roles[$i].policy_file" "${MANIFEST}")
  token_ttl=$(yq -r ".roles[$i].token_ttl" "${MANIFEST}")
  token_max_ttl=$(yq -r ".roles[$i].token_max_ttl" "${MANIFEST}")
  secret_id_ttl=$(yq -r ".roles[$i].secret_id_ttl" "${MANIFEST}")
  secret_id_num_uses=$(yq -r ".roles[$i].secret_id_num_uses" "${MANIFEST}")

  policy_name="${policy_file%.hcl}"
  policy_path="${POLICIES_DIR}/${policy_file}"

  if [[ ! -f "${policy_path}" ]]; then
    echo "Error: policy file not found: ${policy_path}" >&2
    exit 1
  fi

  echo "==> [${name}] policy: ${policy_name}"
  vault policy write "${policy_name}" "${policy_path}" > /dev/null

  echo "==> [${name}] approle role"
  vault write "auth/approle/role/${name}" \
      token_policies="${policy_name}" \
      token_ttl="${token_ttl}" \
      token_max_ttl="${token_max_ttl}" \
      secret_id_ttl="${secret_id_ttl}" \
      secret_id_num_uses="${secret_id_num_uses}" \
      > /dev/null

  role_id=$(vault read -field=role_id "auth/approle/role/${name}/role-id")
  env_var=$(echo "${name}" | tr '[:lower:]-' '[:upper:]_')
  ROLE_IDS_SUMMARY="${ROLE_IDS_SUMMARY}${env_var}_ID=${role_id}
"
  echo "    role_id: ${role_id}"
  echo "---"
done

echo ""
echo "Done. Roles applied: ${count}"
echo ""
echo "Copy the role_id into .env (it's not a secret, safe to store in the open):"
echo ""
printf '%s' "${ROLE_IDS_SUMMARY}"
echo ""
echo "secret_id is NOT generated by this script - bootstrap-approle.sh issues it"
echo "fresh on every docker-compose startup (see README)."

# --- Database Secrets Engine: dynamic Postgres connections + roles ---
#
# Independent of the AppRole loop above. A database_connections entry needs
# an admin credential to already exist in KV (e.g. secret/postgres) - written
# manually in VAULT-GUIDE.md step 3, before this script ever runs.

db_conn_count=$(yq '.database_connections // [] | length' "${MANIFEST}")

if [[ "${db_conn_count}" -gt 0 ]]; then
  echo ""
  echo "Found database connections in manifest: ${db_conn_count}"
  echo "---"

  vault secrets enable database 2>/dev/null || true

  for i in $(seq 0 $((db_conn_count - 1))); do
    name=$(yq -r ".database_connections[$i].name" "${MANIFEST}")
    plugin_name=$(yq -r ".database_connections[$i].plugin_name" "${MANIFEST}")
    connection_url=$(yq -r ".database_connections[$i].connection_url" "${MANIFEST}")
    admin_kv_path=$(yq -r ".database_connections[$i].admin_kv_path" "${MANIFEST}")
    admin_username_field=$(yq -r ".database_connections[$i].admin_username_field" "${MANIFEST}")
    admin_password_field=$(yq -r ".database_connections[$i].admin_password_field" "${MANIFEST}")
    allowed_roles=$(yq -r ".database_connections[$i].allowed_roles" "${MANIFEST}")

    admin_username=$(vault kv get -field="${admin_username_field}" "secret/${admin_kv_path}")
    admin_password=$(vault kv get -field="${admin_password_field}" "secret/${admin_kv_path}")

    echo "==> [${name}] database connection (plugin: ${plugin_name}, admin: secret/${admin_kv_path})"
    # verify_connection=false: this script runs at Step 5, before `docker
    # compose up -d` (Step 6) has started the `postgres` container - the
    # hostname in connection_url can't resolve yet. Skips the live check at
    # config-write time; Vault connects for real on the first actual
    # database/creds/<role> request, by which point postgres is up (the
    # keycloak-db-init -> vault-agent-keycloak dependency chain in
    # docker-compose.yaml guarantees that ordering - see VAULT-GUIDE.md 6.1).
    vault write "database/config/${name}" \
        plugin_name="${plugin_name}" \
        connection_url="${connection_url}" \
        verify_connection=false \
        allowed_roles="${allowed_roles}" \
        username="${admin_username}" \
        password="${admin_password}" \
        > /dev/null
    echo "---"
  done
fi

db_role_count=$(yq '.database_roles // [] | length' "${MANIFEST}")

if [[ "${db_role_count}" -gt 0 ]]; then
  echo ""
  echo "Found database roles in manifest: ${db_role_count}"
  echo "---"

  for i in $(seq 0 $((db_role_count - 1))); do
    name=$(yq -r ".database_roles[$i].name" "${MANIFEST}")
    db_connection=$(yq -r ".database_roles[$i].db_connection" "${MANIFEST}")
    creation_statements=$(yq -r ".database_roles[$i].creation_statements" "${MANIFEST}")
    revocation_statements=$(yq -r ".database_roles[$i].revocation_statements" "${MANIFEST}")
    default_ttl=$(yq -r ".database_roles[$i].default_ttl" "${MANIFEST}")
    max_ttl=$(yq -r ".database_roles[$i].max_ttl" "${MANIFEST}")

    echo "==> [${name}] database role (connection: ${db_connection}, ttl: ${default_ttl}/${max_ttl})"
    vault write "database/roles/${name}" \
        db_name="${db_connection}" \
        creation_statements="${creation_statements}" \
        revocation_statements="${revocation_statements}" \
        default_ttl="${default_ttl}" \
        max_ttl="${max_ttl}" \
        > /dev/null
    echo "---"
  done

  echo ""
  echo "Database roles applied. Verify with, e.g.: vault read database/creds/keycloak_role"
  echo "Note: the target role (e.g. keycloak_owner) referenced in creation_statements"
  echo "must already exist in Postgres before the first credential request - the"
  echo "keycloak-db-init container creates it on every docker-compose startup."
fi